[package]
org = "ballerina"
name = "persist_tools"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["wrappers"]
repository = "https://github.com/ballerina-platform/persist-tools"
license = ["Apache-2.0"]
distribution = "2201.0.4"
export = ["persist_tools"]

[[platform.java11.dependency]]
path = "../native/build/libs/persist-tools-native-@project.version@.jar"
